# Place holder for creating the scm test receipe
[service.setup]
name = ["apache2"] 
action= ["install", "enable"]

[service.ops]
name = ["apache2"]
action =["restart"]


[directory.list]
name = ["/etc/apache","/etc/apache2"] 
params = {'owner'='root','group'='root','mode'= '0755'}
action = ['create']
notifies = "@format {this.service.ops}"


[directory.conf]
name = ["/etc/apache3","/etc/apache25"] 
params = {'owner'='root','group'='root','mode'= '0755'}
action = ['create']
notifies = "@format {this.service.ops}"


[file.conf]
name = ["/var/www/customers/public_html/index.php"]
action = ["create"]
content  = "This is the test file"
params = {'owner'= 'root','group'= 'root','mode' = '0755'}
notifies = "@format {this.service.ops}"


[file.test]
name = ["/var/www/customers/public_html/index.php"]
action = ["create"]
content  = "This is the test file"
params = {'owner'= 'root','group'= 'root','mode' = '0755'}
notifies = "@format {this.service.ops}"
